# It contains all the configs required in the project
data:
  source_url :  "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  local_dir : data
  data_filename : data.zip
  unzip_data_dir : data #Currently the data is being extracted at the same filepath. This variable can be changed to move the extracted data elsewhere
  bad_data_dir : bad_data
  parent_data_dir : PetImages
  model_dir : model
  initial_model_file : init_model.h5


params:
  #img_shape : (180,180,3) When enclosed with square brackets, it is assumed as a string and not tuple.Therefore []
  img_shape : [180,180,3]
  lr : 0.001
  loss_function : sparse_categorical_crossentropy
  metrics : ["accuracy"]
